### ISSUE TITLE
0.3.0 Duplicat CO2 value and rearrange values issue

### ISSUE THREAD

**Issue by DJay-X** [skrollme/homebridge-eveatmo#10]
Hmm... with me the CO2 content is displayed twice. From a friend I've heard that temperature is double instead. 

And when I want to sort the entries in a different order, the app will ignore that and then sort them again as it was.
Apart from that everything looks very good after I took tts out completely last night. Thanks again.

[https://youtu.be/EhPKh4s71hc](https://youtu.be/EhPKh4s71hc)

[https://youtu.be/JrFo2p2-PZk](https://youtu.be/JrFo2p2-PZk)

![5ee81429-b54a-438f-82cb-1ac18676d386](https://user-images.githubusercontent.com/3874239/36305536-4823c216-1314-11e8-80c3-23acb9a400c5.jpeg)

**Comment by skrollme** [comment]
I have no idea concerning the duplicate temperature display 😅 but please check the just published update to 0.3.1. This should deal with the duplicate CO2 characteristic.  At least it is gone for me now. Downside: Apple's stock Home.app does not display the CO2 value inside the AirQuality service anymore.
Besides the 0.3.1 update try setting the "extra_co2_sensor" config to false. It seems, that you have some more characteristics than me:
![img_7d3f1ea91c85-1](https://user-images.githubusercontent.com/1336659/36339809-ad7f3f78-13cd-11e8-9d6d-b3b9af314595.jpeg)

**Comment by DJay-X** [comment]
Thanks. Works! :)
