### ISSUE TITLE
getStationsDataError error: Access token expired

### ISSUE THREAD

**Issue by septeven** [skrollme/homebridge-eveatmo#17]
Hi there,
I installed your plugin yesterday for the first time - It was working very well but it's been a few minutes (problem may be older) that I noticed everything was labelled "no responding" in the app Home. 

I found the following error in the logs : 
[evatmo platform] WARN - Netatmo: Error: getStationsDataError error: Access token expired

Any chance you let me know what went wrong?

**Comment by skrollme** [comment]
Hello @septeven ,
I also got the "Access token expired" error once, but that was after not restarting homebred or the raspberryPi it runs on for half a hear or so. Does it start working again (for longer) after restarting homebridge?

**Comment by septeven** [comment]
Hi @skrollme 
Thanks for your response.
Yes, I restarted the raspi and it seems working well for now - I will let you know if the error pops up again.
