### ISSUE TITLE
Missing history data fir indoor/outdoor moduled

### ISSUE THREAD

**Issue by Phoenix-DH** [skrollme/homebridge-eveatmo#20]
Hi,

I checked the plugin.
I have only history data for the main station.
For the outdoor and a second indoor module there is no history data.

Is this missing in general or an error at my end?

Thanks

**Comment by skrollme** [comment]
I have the same module setup (1x base-station, 1x outdoor-module + 1 additional indoor module) and the history works for me on all modules. Please try restarting homebridge or wait a little bit until more history data were recorded. Maybe the get displayed then.

**Comment by Phoenix-DH** [comment]
Everything is running since months... no history on additional modules ...

**Comment by Phoenix-DH** [comment]
Sorry, didn‘t answered for others...
Already tried... that was the solution.

Thanks.
