### ISSUE TITLE
Low battery warning

### ISSUE THREAD

**Issue by gazzmanzx6** [skrollme/homebridge-eveatmo#21]
Having replaced the batteries in one of the modules Eve is still showing the low battery warning.
Is there a way to clear this?

Other than that eveatmo is working great.
Thanks.

**Comment by skrollme** [comment]
I'm not sure if the battery warning is always updated directly. I will look into this.

If it is not fixed until now by itself, try restarting homebridge as workaround.

**Comment by gazzmanzx6** [comment]
Thanks for the reply.
It didn't clear itself but restarting homebridge has cleared the warning.
Thank you.

**Comment by skrollme** [comment]
I just looked into this and I might have found a fix for this. I will publish this soon.

**Comment by skrollme** [comment]
Version 0.4.2 was just published.
