### ISSUE TITLE
Set threshold for extra CO2 

### ISSUE THREAD

**Issue by palasinio** [skrollme/homebridge-eveatmo#24]
Hi,

wasn‘t there a way to set a threshold for the extra co2 sensors? 1000 is a bit to low.

Regards,

**Comment by skrollme** [comment]
At the moment there is no configuration-option to change the co2 trigger threshold. I will add this to the ToDo list

**Comment by skrollme** [comment]
Done in 0.4.3 (https://github.com/skrollme/homebridge-eveatmo/releases/tag/0.4.3)

**Comment by palasinio** [comment]
Nice! THX!

**Comment by nielsth** [comment]
Great, thanks!

**Comment by JacVid** [comment]
Thanks a lot !
