### ISSUE TITLE
Keep saying token has expired after sometime until reboot

### ISSUE THREAD

**Issue by nicoduj** [skrollme/homebridge-eveatmo#25]
I had this error today, the plugin was  saying that the access token has expired. Restarting homebridge fixed that. Just beofre it begun,I had an error retrieving data from netatmo (which happens sometimes)
![74d0e3c8-089a-42f8-b866-a4183b8ac3fa](https://user-images.githubusercontent.com/19813688/51410732-c6a72380-1b65-11e9-9900-a1aef152223f.png)

**Comment by skrollme** [comment]
This did not happened to me before, but most netatmo-API problems are caused by server-problems on netatmo's side. Also the authentication is completely handled inside the netatmo-library (https://github.com/karbassi/netatmo) so maybe the creator of this plugin can help on this.
