### ISSUE TITLE
CO2 Sensor data

### ISSUE THREAD

**Issue by JacVid** [skrollme/homebridge-eveatmo#26]
Hello and thanks a lot for your job ! It is very usefull...

May I suggest an update regarding the CO2 Sensor. Via Apple Home App, to get the CO2 value, you have to keep pressing on the CO2 Sensor square button, then press setting and then you have the level in ppm. Could this status be directly display in the CO2 Sensor square button, in the same way as Humidity and Air Quality?

Thank you in advance.

**Comment by nielsth** [comment]
I'm not sure if this is supported by HomeKit. Binary sensors generally don't show values in their tile, only regular sensors (such as Air Quality, Light/lux, Humidity) do.

**Comment by JacVid** [comment]
Thanks for your answer. Does it mean, it won't be possible at all ?

**Comment by skrollme** [comment]
@JacVid the display of the measurements is defined as is by the home.app. There is no way for an accessory to define where/how it's values are displayed, as far as I know.

I would suggest to use an other HomeKit app, like [Eve](https://itunes.apple.com/de/app/eve-für-homekit/id917695792?mt=8).
