### ISSUE TITLE
Home Assistant?

### ISSUE THREAD

**Issue by jbk1988** [skrollme/homebridge-eveatmo#27]
Hi,

I'm very new to programming, and I wanted to figure out if there is a way to adapt this to Home Assistant. Do you have any suggestions?

Thanks!

**Comment by skrollme** [comment]
Hi,
what do you especially mean with "... adapt **this** to Home Assistant..."? I personally never used _Home Assistant_ before, but I found a Netatmo connector in it's component-library (https://www.home-assistant.io/components/netatmo/). I do not know what features this component supports and how it looks like when it is working. My suggestion would be to simply try it out and if the component does not (everything) what you want, start looking here: https://developers.home-assistant.io/docs/en/hassio_addon_index.html

Good luck and best regards
