### ISSUE TITLE
Disable outdoor Module

### ISSUE THREAD

**Issue by solbadguy2010** [skrollme/homebridge-eveatmo#29]
Hi,
I have a defective Outdoor Module but the Indoor one is running fine. Is there a setting that disables the two outdoor Values in Homebridge, so that only indoor values are visible in The Home App?

If not, could you add one, please :-)

Timo

**Comment by skrollme** [comment]
You can add a "blacklist" node to the eveatmo-platform in the homebridge-configuration to exclude specific devices. You have to use the device-ids here. Example:

```
...
"platforms": [
        {
            "platform": "eveatmo",
            "name": "eveatmo",
            "ttl": 540,
            "blacklist": [
                "01:23:45:67:89:AB",
                "CD:EF:01:23:45:67"
            ],
            "auth": {
...
```

I will add the description to the plugins README soon.
