### ISSUE TITLE
My Netatmo Username is a Email Adress and config.json wrong?

### ISSUE THREAD

**Issue by bam2000** [skrollme/homebridge-eveatmo#3]
hi,
i wanted to install this nice plugin to use my Netatmo Weather Station with Apple HomeKit.
I have installed the Plugin, but when i create the config.json file with alle the necessary data in it, the home bridge tells me that there is an error with my file and i should check it on https://jsonlint.com
With your sample config i get the following error: Error: Parse error on line 1:
"platforms": [{	"platform": "e
-----------^
Expecting 'EOF', '}', ',', ']', got ':'

And with the modified config.json from the home bridge sample data i get an error with my username.
Because i don't have a username i have to use my email address and so its telling me the @ is wrong.
Is there anything i can do ?
i have found out that Netatmo has some problems right now with the API, but i think my problem is something else because with a config.json my Homebridge doesn't even load :(

Thanks for the help

Carsten

**Comment by skrollme** [comment]
From your description and the error-message, this seems just to be an problem with your _config.json_. As it said, check jsonlint or another json-validator or json-formatter. If you are on MacOS you can for example use the Texteditor [Textmate](https://macromates.com). It has an integrated json-checker/-formater. But there a lots of others out there you can use.
I would recommend to start with a small _config.json_ and add one accessory or platform at a time.

**Comment by bam2000** [comment]
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"description": "This is an example configuration file with all supported devices. You can use this as a template for creating your own configuration file containing devices you actually own.",

"accessories": [
    
],

"platforms": [
    {    "platform": "eveatmo",
        "name": "eveatmo platform",
       "ttl": 15,
       "auth": {
           "client_id": "my id",
           "client_secret": "my secret key",
           "username": "my Email",
           "password": "my password"
    }
   
]
}


i can't get it to work, my config looks like this, but my home bridge won't start and just tells me There was a problem reading your config.json file....

I dont understand what https://jsonlint.com want me to change.

Can you help me please :(

**Comment by skrollme** [comment]
> edit: got it :)

Good to hear that ;)
