### ISSUE TITLE
Help needed: Eve Motion and Eve Room

### ISSUE THREAD

**Issue by HomeKidd** [skrollme/homebridge-eveatmo#31]
Hi!

I'm working on implementing custom Eve characteristics for ESP8266 based HomeKit firmware that works without any bridge via Wi-Fi.

Currently I've successfully added Eve Degree (shows up as "real" Degree in Eve app), but i can't find the correct order for Eve Room! But i've found some things in Accessory Simulator, e.g: VOC density doesn't shows up on Eve app (Room's sensor can measure it...also CO2) 
But VOC characteristic will be kept because I've the same sensor that Elgato have in Room😄 

Other thing that cant figure out is Eve Motion have ( had???) custom **"LED on Motion" characteristic** for toggeling the LED when motion detected.... anybody found the proper characteristic for that? 
It would be a nice feature to turn on/off the led when motion detected via Eve's characteristic 😄 

Eve Motion characteristic:
![IMG_7749](https://user-images.githubusercontent.com/53994826/67028651-ffcbee80-f10b-11e9-97c4-64e8c9561a7e.JPG)

**Comment by skrollme** [comment]
Sorry for the late response, I was on vacation. But unfortunately I cannot help you with with. Neighter I have a Eve Motion by myself nor I have some knowledge about the special characteristics of the EVE Motion.
