### ISSUE TITLE
Sonometer Featurerequest 

### ISSUE THREAD

**Issue by pitleh** [skrollme/homebridge-eveatmo#33]
Would it be possible to add the sonometer data to the plugin? Was not mentioned anywhere.

Thanks

**Comment by skrollme** [comment]
Because _homebridge-eveatmo_ aims more to mimic an _eve_-device this functions is not included here. Bu you can use this original _homebridge-netatmo_ plugin, which already supports the sonometer: https://github.com/planetk/homebridge-netatmo
