### ISSUE TITLE
Exclude items from being passed over to HomeKit

### ISSUE THREAD

**Issue by G60GT** [skrollme/homebridge-eveatmo#37]
Hi,

now that the (v3) Weather Station is officially HomeKit compatible, is it possible to add an option to hide certain components from HomeKit? I'd like to continue using homebridge-eveatmo to get the (officially unsupported) readings from rain and wind gauge into Eve, including history. But I don't really need the duplication of the Main, indoor and outdoor modules. So, if there were a way to only expose the rain and wind gauge, that would be fantastic!

**Comment by skrollme** [comment]
You can try to use black/whitelists like in the original-plugin. See the following documentation:
https://github.com/planetk/homebridge-netatmo#control-accessories-by-device-id

**Comment by G60GT** [comment]
I don't see how that would work, as only the Main Module has a MAC address you could blacklist. But then the readings from the rain and wind gauge would be gone, too.

**Comment by skrollme** [comment]
The MAC address you see there is not the network's MAC-address (I know, it's missleading). It is an Netatmo internal MAC address. Every module should have this as well. To get these, do a sample request [here](https://dev.netatmo.com/apidocumentation/weather#getstationsdata) when logged in. You should get a list with all modules and their addresses.

**Comment by G60GT** [comment]
Thanks for the info. Didn't know (or deduce from the readme of the original plugin) that you have to get the module-specific MACs (IDs) from the dev center.

It works - that's great! Again, thank you very much!

**Comment by skrollme** [comment]
I will add some information on this to the _homebribge-eveatmo_ readme
