### ISSUE TITLE
After update Hombridge UI X this plugin causes all accessories not responding

### ISSUE THREAD

**Issue by miquellaboria** [skrollme/homebridge-eveatmo#38]
After update Hombridge UI X this plugin causes all accessories not responding, after remove config all works again.

**Comment by skrollme** [comment]
Hello @miquellaboria ,
I'm not sure if we are using the same ConfigUI but I'm using homebridge-config-ui-x and just updated to v4.10.3. Everything is still working for me.

**Comment by miquellaboria** [comment]
Hi @skrollme,
Yes it‘s the same, I downgrade Hombridge UI X and have the same issue... I don’t know why, but when I add Config data ALL accessories have no response :(

**Comment by miquellaboria** [comment]
I have the outside sensor sometimes disconnects, can be this the cause?

**Comment by skrollme** [comment]
The plugin's logic is based heavily on the fact, that all modules are present in the Netatmo-API Response at startup. If this is not the case in your setup, try restarting it when the outdoor-module is in reach.

**Comment by miquellaboria** [comment]
When I fix outdoor module all works fine...

**Comment by skrollme** [comment]
Great to hear that. I'm sorry for the inconveniences..
