### ISSUE TITLE
Netatmo Rain Gauge

### ISSUE THREAD

**Issue by Marfre888** [skrollme/homebridge-eveatmo#42]
Hi,

Thank you for this plugin, as for some reason, despite the weather station v3 being supported by homekit, the rain gauge still shows up as not supported, and thanks to your plugin it is at least able to be controlled by eve.

My main idea for getting the weather station was to close my windows automatically when it is raining. Unfortunately, I can't get them to close with this plugin either. Would it be possible to add an On/Off switch or occupation sensor that points out if it is currently raining or not.

Thanks

**Comment by skrollme** [comment]
Hey @Marfre888 ,
that is quite a good idea to implement a "is it raining" switch/indicator to enable such automations.
I will add it to the ToDo-List for the plugin, but recently I rarely using it by myself at all. So it could take a while that this will become reality.

**Comment by danny1605** [comment]
how long will it take. approximately.

**Comment by Marfre888** [comment]
@skrollme Thank you for your message. As the rainy season starts coming in. Would it be possible to integrate this feature?

In reality a, if 'rain last hour' = 0mm occupancy sensor OFF, otherwise ON, would work great. There is no need for it to be super specific.

 It would at least make it possible to close my windows if I'm not home and it starts raining, which is all I'm after.

Thanks :)

**Comment by fwiehl** [comment]
Is it right, that the rain Gauge isn't supported by homebridge yet?
I'm using homebridge with eveatmo plugin. The rain sensor is showing in Apple Home as "not supported".

**Comment by julien94800** [comment]
Hello,
It is supported by homebridge. But not supported by Apple Home app. In order to see the accessory fully working, you should have a look on the Eve app. There you will see that even if not supported in Home app, it is fully supported there

**Comment by fwiehl** [comment]
Oh, yes, I've recognized the rain sensor in EVE app. It is very sad, because all other things works with Apple Home App...

**Comment by firebowl** [comment]
Also just noticed that the rain sensor in the Home App is displayed as not supported. This is not bad but annoying because I can't hide the rain sensor in the Home App. Is there a way to disable the rain sensor in the plugin? I find it a bit annoying to have an unsupported device in the favorites of the Home App and can't hide it.

**Comment by skrollme** [comment]
You can only disable ([blacklist](https://github.com/skrollme/homebridge-eveatmo#control-accessories-by-device-id)) a certain device completely for HomeKit. If you do so it won't be present in Home.app AND EVE.app.
There is no possibility to do this on a per-app-basis, sorry.

**Comment by firebowl** [comment]
Thanks, that was the solution. I could have just finished reading the documentary. ;)

**Comment by clipse2004** [comment]
Hi, 
i have already same problem, but where can i find the mac adress from rain and wind sensor? I only can find serialnumber. 
When i add these to blacklist it didnt work.

**Comment by skrollme** [comment]
Hey @clipse2004 ,
try this way:
- https://dev.netatmo.com and login
- https://dev.netatmo.com/apidocumentation/weather
- click `/getstationsdata`
- click `Try it out`
- click `Execute /getstationsdata`
- you should see a longer dataset on the bottom, look for the modules you want to blacklist and take the `_id` values as MAC

**Comment by clipse2004** [comment]
i can see the modules and blacklisted but you can see on the pictures thats already there. Did you connect your bridge via HomeKit (Station v3) and this plugin?
thats really beautifull, they sell a product "with HomeKit" and now this :/
![Bild](https://user-images.githubusercontent.com/47680803/100473598-07b3db80-30df-11eb-87e0-bad3e2ee4da3.png)
![Bild1](https://user-images.githubusercontent.com/47680803/100473601-0b476280-30df-11eb-9ec0-8f932b281e82.png)

i think i should write to support :(

thanks for your help

**Comment by clipse2004** [comment]
Ok I have a Solution! 
Go on a iMac, Mac mini or MacBook under Home, there is it possible to deactivate.

Just for information, there will certainly be even more such requests ;)

**Comment by skrollme** [comment]
Thanks for your feedback, @clipse2004. I will keep it in mind for the next request ;)

**Comment by The-Paw** [comment]
> Ok I have a Solution!
> Go on a iMac, Mac mini or MacBook under Home, there is it possible to deactivate.
> 
> Just for information, there will certainly be even more such requests ;)

Here is no option for deactivation .. home-app in bigsur on mscbookair
