### ISSUE TITLE
No co2, wind, rain

### ISSUE THREAD

**Issue by gungner** [skrollme/homebridge-eveatmo#43]
First of all, THANKS! My connection to netatmo works and it starts its initializing start of with all weather modules

<img width="904" alt="Screenshot 2020-09-22 at 11 57 10" src="https://user-images.githubusercontent.com/6198782/93868774-3cfd1100-fccb-11ea-8585-b014056c658d.png">

However, only battery, temp and humidity shows up in my HOOBS. No co2, wind, rain. I understand that it should from the description hence this issue report.

MFG Tord

**Comment by skrollme** [comment]
Hello Tord, 
I have no experience with HOOBS and never tested it or even know about how it works internally. So I can not give any advice on this. I personally use my homebridge-eveatmo plugin in a native homebridge-setup on a RaspberryPi and for me my rain-sensor works. 
Concerning the CO2 Sensor: Have you enabled the extra CO2 sensor for HomeKit in the config?
`...
extra_co2_sensor: true,
...`

**Comment by gungner** [comment]
Hi, HOOBS is just a layer on top of homebridge, like a supervisor . Yes I’ve enabled extra co2. I did get an high level co2 alarm through homekit but I can’t read any live values.  I’ll try it on a native homebridge installation. 

Mfg tord

**Comment by skrollme** [comment]
Have you already tried using the Homekit App from Eve? The homebridge-eveatmo plugin was designed to work with this (custom characteristics, measurement history, ...)

**Comment by gungner** [comment]
Long time ago, I’ll try it again. Thinking of migrating from Hassio to homebridge (Hoobs). Thanks.

MFG tord

**Comment by gungner** [comment]
Now I've tried it with EVE, all information is there :) Thanks a lot 

MFG Tord
