### ISSUE TITLE
Accessory out of compliance on iOS 14.1+

### ISSUE THREAD

**Issue by nberardi** [skrollme/homebridge-eveatmo#47]
I am getting an accessory out of compliance on iOS 14.1+ when I have this plugin installed.  I was able to track it down to this plugin on my Homebridge setup after wiping my installation clean and slowing adding new plugins until one broke the experience.  If there is any debugging I can do to help with this bug please let me know.

**Comment by skrollme** [comment]
Interesting, never happened to me before. So...
- Which Homebridge Version you use
- Which version of my plugin you use
- In which app/log you see the notification

**Comment by nberardi** [comment]
@skrollme thanks for the response

**Which Homebridge Version you use.**

I am using Homebridge 1.1.6, also tried with 1.2.3 with the same results.  Additionally I tested it out on HOOBS with the same result.  https://www.reddit.com/r/HOOBS/comments/iwfgc3/accessory_out_of_compliance/garpoui/?context=3

**Which version of my plugin you use**

I was using the latest one published to NPM => 0.5.0 (2020-01-05).

**In which app/log you see the notification**

This accessory out of compliance issue comes up in iOS 14.1+ in the home app when try to add the homebridge to the HomeKit app.  The screen looks like this.

![issue](https://community-assets.home-assistant.io/optimized/3X/d/b/db9343b1e6d6cf920c18fbb6ad338450b854764a_2_473x1024.jpeg)

**Comment by havman-x** [comment]
I confirm what @nberardi experienced, with the same versions. I pretty much went through the same steps narrowing down to the eveatmo plugin, but have some additional input:
 - tested on a (non-docker) Pi 4, as well as in docker on Synology NAS
 - tried to add a clean Homebridge with eveatmo on iOS 12.4.9 also, but without success. Different error message than "out of compliance" though
 - managed to get it working again with Homebridge 1.3.0.beta-24 and 1.3.0.beta-25, with homebridge-config-ui-x v4.33.0 + homebridge-eveatmo v0.5.0 + Node.js v12.19.0 in docker on the NAS. I did not test these versions on the Pi though.

**Comment by skrollme** [comment]
The reason why I did not see this kind of warning so far is, that I'm using my current setup (paired with HomeKit as bridge) for a long time. 
Doe it work if you add Homebridge to HomeKit first, and then adding eveatmo followed by a restart? It could also may help if you exclude unsupported accessories (wind, rain) via blacklisting (https://github.com/planetk/homebridge-netatmo#control-accessories-by-device-id)

**Comment by dnx231** [comment]
I'm facing the same problem. Can't pair Homebridge with configured Eveatmo Plugin. Without configured Plugin i was able to pair my Homebridge.

I also tried to configure the Plugin after i successfully paired the Homebridge. After a restart HomeKit can't reach any device from my Homebridge.

Using the following Configuration:
Homebirdge v1.1.6
Node.js v14.15.0
npm v6.14.8

On a Pi3

**Comment by AgentMax81** [comment]
Same for me running Homebirdge v1.1.6 on macOS 10.15.7

At first today the unsupported sensors appeared again as favorites. After an hour later
home bridge was not accessible anymore. A few moments before Homebridge UI was updated to v4.34.0

Set it up from the scratch again to figure out it stops working after eveatmo is configured.

**Comment by Dobryash** [comment]
The same problems. I can't add homebridge to my house when using eveatmo.
iOS14.1 
Hoobs 3.2.10
Eveatmo 0.5.0

**Comment by skrollme** [comment]
Has anyone tried [blacklisting](https://github.com/skrollme/homebridge-eveatmo#control-accessories-by-device-id) for example the Rain-Gauge or a Wind-Sensor (if present)? Does the problem still occurs then?

**Comment by Dobryash** [comment]
The same problems. I can't add homebridge to my house when using eveatmo.
iOS14.1 
Hoobs 

> Has anyone tried [blacklisting](https://github.com/skrollme/homebridge-eveatmo#control-accessories-by-device-id) for example the Rain-Gauge or a Wind-Sensor (if present)? Does the problem still occurs then?

Only the internal module is installed.

**Comment by havman-x** [comment]
> I confirm what @nberardi experienced, with the same versions. I pretty much went through the same steps narrowing down to the eveatmo plugin, but have some additional input:
> 
> * tested on a (non-docker) Pi 4, as well as in docker on Synology NAS
> * tried to add a clean Homebridge with eveatmo on iOS 12.4.9 also, but without success. Different error message than "out of compliance" though
> * managed to get it working again with Homebridge 1.3.0.beta-24 and 1.3.0.beta-25, with homebridge-config-ui-x v4.33.0 + homebridge-eveatmo v0.5.0 + Node.js v12.19.0 in docker on the NAS. I did not test these versions on the Pi though.

Did some further tests:
 - Pi 4 with Homebridge v1.2.4/1.2.5, homebridge-config-ui-x v4.36.0, Node.js v14.15.3, homebridge-eveatmo v0.6.1: still a problem
 - NAS with Homebridge beta's up to v1.3.0-beta.34, homebridge-config-ui-x v4.36.0, Node.js v14.15.1, homebridge-eveatmo v0.6.1: Works fine

-- | --

**Comment by The-Paw** [comment]
> Has anyone tried [blacklisting](https://github.com/skrollme/homebridge-eveatmo#control-accessories-by-device-id) for example the Rain-Gauge or a Wind-Sensor (if present)? Does the problem still occurs then?

Here the same .. white&black doesn't work :-((

**Comment by skrollme** [comment]
Is this still an open topic for you @nberardi , @havman-x , @dnx231 , @AgentMax81 , @Dobryash , @The-Paw ?

**Comment by AgentMax81** [comment]
> Is this still an open topic for you @nberardi , @havman-x , @dnx231 , @AgentMax81 , @Dobryash , @The-Paw ?

No :)

**Comment by nberardi** [comment]
No

**Comment by havman-x** [comment]
No, i.e. when running on a separate homebridge. It does not work fine on the same homebridge as the other plugins, also not as a child bridge.

**Comment by The-Paw** [comment]
No

**Comment by skrollme** [comment]
ok, thanks for responding

**Comment by ggale13** [comment]
Was there ever a fix for this problem as I am encountering this exact problem using Homebridge v1.6.1, Node.js v18.16.0 running on Mac OS Ventura v 13.3.1 however I have also tried on my Synology Docker and DSM v7. homebridge-eveatmo v1.1.0 -one of my favorite plug-ins and it is frustrating not being able to pair it. Note that I can see the weather data just fine in Homebridge under accessories but it shows Accesory is out of compliance when trying to pair to IOS home app.

Plug-in Configuration
{
    "name": "eveatmo platform",
    "ttl": 540,
    "blacklist": [
        "0E:9B:22:C6:38:BD"
    ],
    "extra_co2_sensor": true,
    "weatherstation": true,
    "airquality": true,
    "co2_alert_threshold": 1000,
    "log_info_msg": false,
    "auth": {
        "client_id": "xxxxxxx",
        "client_secret": "xxxxxxx",
        "grant_type": "password",
        "refresh_token": "xxxxxxxxxxxx",
        "username": "xxxxxx@icloud.com",
        "password": "xxxxxxxxxxx"
    },
    "platform": "eveatmo",
    "_bridge": {
        "username": "0E:E5:83:39:1xxxxxx",
        "port": 44118
    }
}

As you will note above I have attempted to Blacklist my Wind and Rain sensors, however no such luck. 

Any assistance that can be provided would be greatly appreciated. This is a must have plug-in for me.
