### ISSUE TITLE
Unable to remove exposed "unsupported devices" (Rain, Wind) from Favorites

### ISSUE THREAD

**Issue by jostrasser** [skrollme/homebridge-eveatmo#48]
**Describe the bug**
Unable to remove exposed "unsupported devices" (Rain, Wind sensors) from Favorites.
Issue exists since iOS14

**Version you use**
- homebridge version 1.1.6
- node version 14.15
- plugin version 0.5.0

**To Reproduce**

Check favorites in Apple Home App
Klick on an unsupported device
The switch to remove it from Favorites is missing

Thanks!

**Comment by jostrasser** [comment]
Similar issue:
https://github.com/ebaauw/homebridge-hue/issues/767#issuecomment-695763159

**Comment by jostrasser** [comment]
Is there a way to "exclude" these types of sensors?

**Comment by skrollme** [comment]
Hey @jostrasser ,
you can exclude devices via white/blacklisting (see: https://github.com/planetk/homebridge-netatmo#control-accessories-by-device-id)

The _homebridge-eveatmo_ plugin was designed with the focus to work best with HomeKit app from EVE. The default Home.app always came on second place. And as far as I know there is no  way to control an accessories appearance differently for different HomeKit apps.

Concerning your way to reproduce this: I don't have any unsupported accessories in my favorites ;) Why did you even have them there?

**Comment by jostrasser** [comment]
Hi @skrollme 

Thanks, I will try blacklisting the two modules. 

Under iOS 13 I have removed the rain and wind sensor from my favorites. 

A few days ago Netatmo has changed the names of the modules central on their servers:

https://forum.netatmo.com/viewtopic.php?f=5&t=19196

Now the plugin has overwritten all module names with the new name scheme. This forces that the modules were automatically re-added to the favs. 

iOS 14 has lost the capability to "un-fav" the devices and I don't have an old iOS 13 device anymore to remove the unneeded ones. :(

BR/JO!
