### ISSUE TITLE
Notification option for the air quality sensor

### ISSUE THREAD

**Issue by Krocko** [skrollme/homebridge-eveatmo#5]
Is it possible, to add the notification option for the air quality sensor?

**Comment by skrollme** [comment]
Good idea, @Krocko. I will try it and let you know if the package is on npmjs.

**Comment by Krocko** [comment]
Great! Thank you.

**Comment by skrollme** [comment]
I did some research and I think the _Air Quality Sensor_ is (by HomeKit reference) not able to send notifications. But it looks like this could be possible by an _Carbon Dioxide Sensor_ or to be more precise by its _Carbon Dioxide Detected_-Characteristic. This is at least the way [homebridge-netatmo](https://github.com/planetk/homebridge-netatmo) does it. Currently I'm more interested in the default Eve Room/Weather behavior but I will look into this. 

Maybe this will become a config switch: "Add _Carbon Dioxide Sensor_ yes/no"

**Comment by Krocko** [comment]
Agreed. Good idea.

**Comment by skrollme** [comment]
Hey @Krocko. The feature was added in the V0.2.9 release. Please see the [config-sample](https://github.com/skrollme/homebridge-eveatmo#configuration) how to enable the extra _Carbon Dioxide Sensor_

**Comment by Krocko** [comment]
Works. Thank you. Any chance to get the noise Level any air presure from the main module?

**Comment by skrollme** [comment]
You find the main module's airpressure at the outdoor module as it is on the Eve Weather.
Concerning the noise level: I'll put this on the todo-list, but at least for me this is the most superfluous netatmo-metric in Homekit. So: Low-prio!
