### ISSUE TITLE
Will the plugin work with Healthy Home Coach?

### ISSUE THREAD

**Issue by adamrzanek** [skrollme/homebridge-eveatmo#51]
Since I have problems with native readings from netatmo home coach is it possible to integrate it with the plugin?

**Comment by skrollme** [comment]
Hey @adamrzanek , 
since I don't have a Home Coach by myself, I don't think it will happen anytime in the near future, sorry.
If you want to try it by your own, feel free. Pull requests are alway welcome.

**Comment by foliveira** [comment]
Hi @adamrzanek @skrollme 

I've implemented support for the Healthy Home Coach (PR #52) - have it working for a week at least and everything seems fine.

**Comment by adamrzanek** [comment]
@foliveira oh wow! I will try to install it tomorrow for sure. Since official Home Coach implementation is broken (wrong breakpoints) you’re saving me from lot of frustiations ;) @skrollme can you implement it to your plugin?

**Comment by foliveira** [comment]
@adamrzanek as I've mentioned there's an open PR for the support, so it should be easy to try it out. @skrollme let me know if I can help or even change anything

**Comment by azertiv** [comment]
@foliveira Is the Netatmo Home Coach now supported? I don't see anything in the accessories :) Thx !

**Comment by foliveira** [comment]
Hi @azertiv - there’s a PR open to support the Health Coach (#52) - @skrollme should be able to review and give indication if it gets merged back

**Comment by foliveira** [comment]
@skrollme with #52 merged this can be closed 👍
