### ISSUE TITLE
The outdoor module is not displayed with a white list

### ISSUE THREAD

**Issue by Mibra-de** [skrollme/homebridge-eveatmo#53]
Hi there,

I use two Netatmo stations. a version 2 and a version 3.

Now I have everything set up in Homkit and it works too.

Version 2 via evetamo and version 3 via Homkit native.

Version 2 was set as a whitlist so that version 3 runs normally via Homekit.

Unfortunately, version two of the outdoor module via evetatmo is not displayed in Homekit.

Is there a solution to this?

**Comment by skrollme** [comment]
Hey @Mibra-de , 
white/blacklisting is on a per-module-base and not on a per-station-base. So you have to add the ids of every accessory (netatmo-module) you want to whitelistin the config.

**Comment by Mibra-de** [comment]
Thank you it works perfekt!
