### ISSUE TITLE
Show Wind Speed of Gusts from the Wind Sensor in Eve App?

### ISSUE THREAD

**Issue by janni2607** [skrollme/homebridge-eveatmo#59]
Could it be possible to not only show the current wind speed, but also the wind speed of gusts (as shown in the Netatmo app) in the Eve App?

**Comment by skrollme** [comment]
I hope it's not too late 😄 https://github.com/skrollme/homebridge-eveatmo/releases/tag/0.6.5

**Comment by janni2607** [comment]
Wow - cool! I was still waiting for the feature … Thanks!!!
