### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by r32er** [skrollme/homebridge-eveatmo#6]
i got this error. any idea ?

`Sep 11 21:41:30 homebridge2 homebridge[7432]: buffer.js:769
Sep 11 21:41:30 homebridge2 homebridge[7432]: return this.hexWrite(string, offset, length);
Sep 11 21:41:30 homebridge2 homebridge[7432]: ^
Sep 11 21:41:30 homebridge2 homebridge[7432]: TypeError: Invalid hex string
Sep 11 21:41:30 homebridge2 homebridge[7432]: at Buffer.write (buffer.js:769:21)
Sep 11 21:41:30 homebridge2 homebridge[7432]: at fromString (buffer.js:213:18)
Sep 11 21:41:30 homebridge2 homebridge[7432]: at Function.Buffer.from (buffer.js:105:12)
Sep 11 21:41:30 homebridge2 homebridge[7432]: at new Buffer (buffer.js:86:17)
Sep 11 21:41:30 homebridge2 homebridge[7432]: at EveatmoWeatherPressureService.hexToBase64 (/usr/local/lib/node_modules/homebridge-eveatmo/service/eveatmo-weather-pressure.js:95:11)
Sep 11 21:41:30 homebridge2 homebridge[7432]: at EveatmoWeatherPressureService.updateCharacteristics (/usr/local/lib/node_modules/homebridge-eveatmo/service/eveatmo-weather-pressure.js:115:23)
Sep 11 21:41:30 homebridge2 homebridge[7432]: at /usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:166:51
Sep 11 21:41:30 homebridge2 homebridge[7432]: at Array.forEach (native)
Sep 11 21:41:30 homebridge2 homebridge[7432]: at EveatmoWeatherAccessory.applyWeatherData (/usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:164:24)
Sep 11 21:41:30 homebridge2 homebridge[7432]: at EveatmoWeatherAccessory.notifyUpdate (/usr/local/lib/node_modules/homebridge-eveatmo/accessory/eveatmo-weather-accessory.js:100:9)`

**Comment by skrollme** [comment]
At this point I have no idea, no. More details?
- Does this problem occurs everytime you use the plugin?
- Details about your Netatmo-Setup? Which/how many sensors do you have?
- Does the plugin work in the Testing-Mode? (Add config-parameter "mockapi": "eveatmo")
