### ISSUE TITLE
Error: Authenticate error: invalid_request

### ISSUE THREAD

**Issue by jaydisc** [skrollme/homebridge-eveatmo#61]
After some recent updates, Eveatmo stopped working (reports "No Response") and I notice this in the homebridge log:

`[25/05/2022, 8:48:48 pm] [Netatmo Platform] ERROR - Netatmo: Error: Authenticate error: invalid_request`

Then one of these every 30 seconds:

`[25/05/2022, 8:49:04 pm] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.`

I'm experiencing this on v0.6.5, and I tried reverting to v0.6.4, but the same problem & message persists. I'm running homebridge v1.4.1 over Node v16.15.0 on Raspbian 10.12 (based on `cat /etc/debian_version`) on a Pi 4B.

I've also tried resetting my API key and secret, but that made no difference.

**Comment by skrollme** [comment]
Is this still an open topic?

**Comment by jaydisc** [comment]
No. This eventually came good.
