### ISSUE TITLE
hi all, I updated the plugin but homebridge does not start anymore 

### ISSUE THREAD

**Issue by dendoor** [skrollme/homebridge-eveatmo#66]
**Describe the bug**

**Version you use**
- homebridge version 1.51
- node version 16.16.0
- plugin version 1.01

following error occurs ; [eveatmo platform] WARN - Netatmo: Error: getHealthyHomeCoachData error: Application does not have the good scope rights [01/11/2022, 14:35:45] 
[homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

Version 1.0 gave me no problems. I have updated the refresh token like in the description. Can someone help me ?

**Comment by julien94800** [comment]
Hello, when you request the tokens on the Netatmo website, you have to select scopes. Add the one from coach data (in addition of others) and regenerate a token. Then it should work

**Comment by julien94800** [comment]
In order to be sure everything work you can ask the following scopes (list from the previous issue)

read_station read_magellan read_bubendorff read_smarther read_thermostat read_camera read_doorbell read_mx read_presence read_homecoach read_carbonmonoxidedetector read_smokedetector

**Comment by dendoor** [comment]
OK, I update the token and this is what I get ;

[eveatmo platform] WARN - Netatmo: Error: Authenticate refresh error: invalid_grant
[01/11/2022, 15:21:11] [eveatmo platform] WARN - Netatmo: Error: getStationsDataError error: Invalid access token
[01/11/2022, 15:21:12] [eveatmo platform] WARN - Netatmo: Error: getHealthyHomeCoachData error: Invalid access token
[01/11/2022, 15:21:29] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

**Comment by dendoor** [comment]
You can select an ACCES TOKEN or a REFRESH TOKEN. I am surprised that the ACCES TOKEN is not asked in the configuration. Only the REFRESH TOKEN (what I did). Do I mis something ? What about the ACCES TOKEN ?

**Comment by dendoor** [comment]
I did a reset of my client ID and client secret, and also asked for a REFRESH TOKEN. When I input these values in de configuration I still get the same errors. Don't know what the problem is....

**Comment by sosko4000** [comment]
I have the same issue. After the upgrade of Homebridge Eveatmo to v1.0.1 and following the instructions for new Netatmo authentication (generate refresh token...) I am getting the same error as @dendoor:
[11/1/2022, 2:27:51 PM] [eveatmo platform] Initializing eveatmo platform...
[11/1/2022, 2:27:54 PM] [eveatmo platform] Loading new data from API for: weatherstation
[11/1/2022, 2:27:54 PM] [eveatmo platform] Loading new data from API for: airquality
 . . .
[11/1/2022, 2:27:54 PM] [eveatmo platform] WARN - Netatmo: Error: Authenticate refresh error: invalid_grant
[11/1/2022, 2:27:54 PM] [eveatmo platform] WARN - Netatmo: Error: getHealthyHomeCoachData error: Invalid access token
[11/1/2022, 2:27:54 PM] [eveatmo platform] WARN - Netatmo: Error: getStationsDataError error: Invalid access token

There is no option in the Settings to add the Access token. Can/should it be added manually in the config somehow? 
Please advice.
Btw I tried to set the refresh token scope to:
1. read_station only
2. set all read options (read_station, read_magellan, read_bubendorff, read_smarther,...)
3. set all available options
It always and up with the same error. 

Thanks

**Comment by sosko4000** [comment]
forgot to mention the relative versions:
Homebridge v1.5.1
Node.js Version v18.12.0
homebridge-eveatmo v1.0.1

Cheers

**Comment by julien94800** [comment]
![image](https://user-images.githubusercontent.com/22552386/199280937-e34bf1c2-e351-480b-ade9-e5d08759a68f.jpeg)

I would suggest trying this. During beta process some other users faced this issue and fixed it. Could you please try this?

**Comment by jcmurty** [comment]
no joy for me either,

as per @sosko4000 above, I have manually confirmed contents of netatmo-token.json match what I created in https://dev.netatmo.com/apps/ using scope read_station

I've tried creating a new app in dev.netatmo.com, no joy

have disabled plugin, manually removed netatmo-token.json, reconfigured plugin, renenabled, restarted, no joy

have uninstalled plugin, removed all traces of it, rinse repeat, no joy

similar error:
[02/11/2022, 2:21:16 pm] [eveatmo platform] WARN - Netatmo: Error: getHealthyHomeCoachData error: Application does not have the good scope rights
[02/11/2022, 2:21:33 pm] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

**Comment by julien94800** [comment]
Hello @jcmurty 
Please try requesting new tokens and be sure adding all the scope when you request it. In your case it seems that you did not select the gethealthyhome scope before generating. You should see a list on previous comment about which scope to select when requesting token

**Comment by v1nc3lx** [comment]
> no joy for me either,
> 
> as per @sosko4000 above, I have manually confirmed contents of netatmo-token.json match what I created in https://dev.netatmo.com/apps/ using scope read_station
> 
> I've tried creating a new app in dev.netatmo.com, no joy
> 
> have disabled plugin, manually removed netatmo-token.json, reconfigured plugin, renenabled, restarted, no joy
> 
> have uninstalled plugin, removed all traces of it, rinse repeat, no joy
> 
> similar error: [02/11/2022, 2:21:16 pm] [eveatmo platform] WARN - Netatmo: Error: getHealthyHomeCoachData error: Application does not have the good scope rights [02/11/2022, 2:21:33 pm] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

Same here.. :/

**Comment by julien94800** [comment]
Hello @v1nc3lx 
Could you please try the following:
Stop your Homebridge instance running this plugin
Delete the Netatmo-token.json file
Request again from netatmo website a refresh token by selecting all scopes
Set all info back to your config
Restart Homebridge 
I hope it will help. In my case it worked like this

**Comment by v1nc3lx** [comment]
> Hello @v1nc3lx
> Could you please try the following:
> Stop your Homebridge instance running this plugin
> Delete the Netatmo-token.json file
> Request again from netatmo website a refresh token by selecting all scopes
> Set all info back to your config
> Restart Homebridge
> I hope it will help. In my case it worked like this

hi @julien94800 and thx

unfortunately it didn't work
i got the same messages:

_Loading new data from API for: weatherstation
Loading new data from API for: airquality
WARN - Netatmo: Error: getStationsDataError error: Application does not have the good scope rights
WARN - Netatmo: Error: getHealthyHomeCoachData error: Application does not have the good scope rights
This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info._

**Comment by typedown** [comment]
Hi there, unfortunately same here_ recreated app at dev.netatmo.com, reinstalled eveatmo plugin in homebridge and deleted all old files for tokens etc. as it stops my HB instance from loading correctly i'ts quite blocking. thank you

**Comment by julien94800** [comment]
Hello @typedown 
In your case do you have the health monitor device too? Or only météo station?

**Comment by v1nc3lx** [comment]
> > WARN - Netatmo: Error: getStationsDataError error: Application does not have the good scope rights
> > WARN - Netatmo: Error: getHealthyHomeCoachData error: Application does not have the good scope rights
> 
> Have you tried deleting your app at dev.netatmo.com and creating a new one with all the rights (scope) you need for your devices, @v1nc3lx ? In doubt, simply request all rights since you are the only user of this app and it shouldn't be a security risk.

thx @skrollme that did the trick!! 🥇

**Comment by typedown** [comment]
> 



> Hello @typedown
> In your case do you have the health monitor device too? Or only météo station?

I'd only the meter station, but I think I found how to do it: I redid all the permissions on dev.netatmo.com and gave access to everything, not only meet. Now it seems to work. Thank you!

**Comment by jcmurty** [comment]
working again for me, as advised regenerated token with all read scopes inc. read_homecoach, deleted netatmo-token.json file, re-enabled plugin, restarted homebridge

**Comment by pitixx** [comment]
In case it's of help to anyone still having the same problem, the file that needs to be edited to ensure the client_id and auth_token match those generated at dev.netatmo.com in the is /var/lib/homebridge/netatmo-token.json. At least that's where it is in my homebridge installation (Raspberry pi).
