### ISSUE TITLE
netatmo-token.js does not present on Mac OS HB

### ISSUE THREAD

**Issue by mrmaximas** [skrollme/homebridge-eveatmo#70]
After plugin upgrade i generate refresh token on netatmo but netatmo-token.js not present in hb config dir or any dir 
[11/15/2022, 4:23:10 PM] [Netatmo] WARN - Netatmo: Error: getStationsDataError error: Invalid access token
[11/15/2022, 4:23:10 PM] [Netatmo] WARN - Netatmo: Error: Authenticate refresh error: invalid_grant
[11/15/2022, 4:23:10 PM] [Netatmo] WARN - Netatmo: Error: getHealthyHomeCoachData error: Invalid access token

**Comment by mrmaximas** [comment]
sorry for delayed answer.
i have generated a refresh_token with the read_station scope and put them
{
            "name": "Netatmo",
            "ttl": 540,
            "extra_co2_sensor": true,
            "weatherstation": true,
            "airquality": true,
            "co2_alert_threshold": 1000,
            "module_suffix": "-",
            "log_info_msg": true,
            "auth": {
                "client_id": "6373919b4de2c7XXXXXXXXX",
                "client_secret": "SIVXgq0VCtmf0BbeR3mxnRd6L4Uq06QXXXXXXXXX,
                "refresh_token": "56b3281067eXXXXXXXXXX|3ef0132XXXXXXXXXXXXXX"
            },
            "_bridge": {
                "username": "0E:34:C8:32:B3:17",
                "port": 44273
            },
            "platform": "eveatmo"
        },
![Screenshot 2022-12-02 at 15 06 58](https://user-images.githubusercontent.com/61165387/205290222-83b08ced-5dac-4b62-a29e-458909fd49fa.png)
"

**Comment by skrollme** [comment]
To me this looks ok, but you could try to run the following steps:
- Shut down home bridge
- Remove `netatmo-token.json` (should be located in home bridge's persist directory, where the config.json is located)
- Create a new App at dev.netatmo.com which all permissions and copy the `client_id` and `client_secret` to your `config.json`
- Also create a new _refresh_token_ and copy it to the `config.json` as well
- Boot homebridge

**Comment by mrmaximas** [comment]
It's works! Thanks and have a good weekend!
