### ISSUE TITLE
Accessory out of compliance in Homekit

### ISSUE THREAD

**Issue by ggale13** [skrollme/homebridge-eveatmo#75]
Was there ever a fix for issue #47?  I am encountering a problem pairing this plugin with my IOS Home app. Everything goes well until I try to pair my Eveatmo child bridge with Homekit and when I try to add it comes up accessory is not in compliance. I am using Homebridge v1.6.1, Node.js v18.16.0 running on Mac OS Ventura v 13.3.1 however I have also tried on my Synology Docker and DSM v7. homebridge-eveatmo v1.1.0 -one of my favourite plug-ins and it is frustrating not being able to pair it. Note that I can see the weather data just fine in Homebridge under accessories but it shows Accessory is out of compliance when trying to pair to IOS home app.

Plug-in Configuration
{
"name": "eveatmo platform",
"ttl": 540,
"blacklist": [
"0E:9B:22:C6:38:BD"
],
"extra_co2_sensor": true,
"weatherstation": true,
"airquality": true,
"co2_alert_threshold": 1000,
"log_info_msg": false,
"auth": {
"client_id": "xxxxxxx",
"client_secret": "xxxxxxx",
"grant_type": "password",
"refresh_token": "xxxxxxxxxxxx",
"username": "[xxxxxx@icloud.com](mailto:xxxxxx@icloud.com)",
"password": "xxxxxxxxxxx"
},
"platform": "eveatmo",
"_bridge": {
"username": "0E:E5:83:39:1xxxxxx",
"port": 44118
}
}

As you will note above I have attempted to Blacklist my Wind and Rain sensors, however no such luck.

Any assistance that can be provided would be greatly appreciated. This is a must have plug-in for me.

**Comment by skrollme** [comment]
Hello @ggale13 ,
I recently moved my setup from an old raspberryPI to my Synology and I'm also running Homebridde 1.6.1 on Node 16. But not as a child-bridge. Since I only have a few accessories I just kept everything in the main-bridge.
Did you already tried to run eveatmo in the main bridge?

**Comment by skrollme** [comment]
And one more question: Do you have any sensors, which are not supported in native Home.app? Like a rain-sensor? Please try to remove them via config's blacklisting and retry to add it to HomeKit again.

**Comment by ggale13** [comment]
I am still having no lock on the out of compliance issue with getting the Eveatmo plugin paired with Homekit. When I add the accessory the Accessory out of Compliance issue comes up. I have now dropped the Child Bridge for this and Blacklisted both the Wind and Rain sensors. Again the pairing with Homekit appears to be the only issue as I am getting the correct Netatmo Weather sensor data in Hombridge on the Accessories page.

Again I have rebooted and reset all I can think of and deleted and reinstalled the plugin with no luck. I would appreciate input from anyone. I also deleted and reinstalled the Apple TV Homekit Hub but no go there either.

**Comment by skrollme** [comment]
ok, thanks for testing. 

> Again the pairing with Homekit appears to be the only issue as I am getting the correct Netatmo Weather sensor data in Hombridge on the Accessories page.

Ok, so - bold question - why bother if it only comes up once during setup? I have never gotten that deep into the nodeJs and  Homebridge-plugin programming. If somebody can point me to problem (in the code) which triggers the warning I will try to fix it. But I have no idea what and how to fix at the moment, and I'm not very invested into this problem because it is no real problem during usage since it is just a warning-popup during setup.

**Comment by ggale13** [comment]
The warning does pop up but it will not allow me to pair with homekit and thus my problem. If it was only a warning and still allowed me to pair, you are correct - I would just ignore the warning and life would be great. It is not the same warning that the accessory is not certified by homekit and may not work properly that you get when adding accessories from non-homekit device through Homebridge where you can just click ok and proceed with the pairing. This warning of non-compliance quits the pairing between the plugin and homekit.

I also have Hoobs and have just recently moved my setup to my M2 Mac Mini. I am going to see if I can use Hoobs and have the plugin pair with Homekit from there. Previously I had and Issue with the Eveatmo plugin getting a refresh token from Netatmo. I will let you know how I make out.

**Comment by ggale13** [comment]
Still hitting a brick wall trying to get the eveatmo plug in to pair with homekit. I believe the issue is related to my wind gauge and rain gauge sensor which I have attempted to blacklist. I am wondering if someone can take a look at my config code to see if I have any errors in the blacklisting - it is not currently. working as I can still see the data in Homebridge from at least one of the two sensors in question. I am hoping that if I can successfully blacklist the two sensors that will then allow me to pair the plugin.

Here is the code I have used.

{
            "name": "eveatmo platform",
            "ttl": 540,
            "Blacklist": [
                "70:ee:50:02:48:54",
                "70:ee:50:04:59:14",
        ],
            "extra_co2_sensor": true,
            "weatherstation": true,
            "airquality": true,
            "co2_alert_threshold": 1000,
            "log_info_msg": false,
            "auth": {
                "client_id": "xxxxxxxxxxxxxx",
                "client_secret": "xxxxxxxxxxxxxxxxxxxxxx",
                "grant_type": "password",
                "refresh_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "username": "ggale13@xxxxxxxxxxx",
                "password": "xxxxxxxxxxxxxxxxxxx"
            },
            "platform": "eveatmo",
            "_bridge": {
                "username": "xx:xx:xx:xx:xx",
                "port": 34121
            }

**Comment by bennovakovic** [comment]
I'm also having this issue. I can't seem to add this plugin on the main bridge, it simply kills all my other plugins when I try to do so. When I add it as a child bridge I get the same compliance warning that @ggale13 is referring to.

**Comment by ggale13** [comment]
Never did find a solution to this. I tried to blacklist wind and rain but had no luck with that. Think I may have the code in the wrong place. I would really love to get this fixed.GarySent from my iPhoneOn Sep 5, 2023, at 05:00, Ben Novakovic ***@***.***> wrote:﻿
I'm also having this issue. I can't seem to add this plugin on the main bridge, it simply kills all my other plugins when I try to do so. When I add it as a child bridge I get the same compliance warning that @ggale13 is referring to.

**Comment by bennovakovic** [comment]
Here is my config. I found my module ids by using the swagger interface on the netatmo website. I then put those into the `whitelist` section.

It took me a while to figure out where the data appeared, but once you click into the room you've assigned the data to, it appears as "Temperature" at the top, not a seperate tile in Homekit.

```
        {
            "name": "eveatmo platform",
            "ttl": 540,
            "extra_co2_sensor": false,
            "weatherstation": true,
            "airquality": false,
            "co2_alert_threshold": 1000,
            "log_info_msg": true,
            "auth": {
                "client_id": "[redacted]",
                "client_secret": "[redacted]",
                "grant_type": "refresh_token",
                "refresh_token": "[redacted]"
            },
            "whitelist": [
                "70:ee:50:3f:aa:01",
                "02:00:00:4f:ff:00",
                "03:00:00:2f:cc:02"
            ],
            "platform": "eveatmo",
            "_bridge": {
                "username": "0E:81:9F:9B:45:B2",
                "port": 36811
            }
        }
```
