### ISSUE TITLE
Problem with the connection to Netatmo API since 2023-12-04

### ISSUE THREAD

**Issue by jostrasser** [skrollme/homebridge-eveatmo#77]
**Describe the bug**
Homebridge unable to start, plugin is preventing start because there are API issues with the Netatmo API.

```
[04/12/2023, 19:26:12] [eveatmo-platform] WARN - Netatmo: Error: getHealthyHomeCoachData error: Invalid access token
[04/12/2023, 19:26:29] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[04/12/2023, 19:26:49] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[04/12/2023, 19:27:09] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[04/12/2023, 19:27:29] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[04/12/2023, 19:27:49] [homebridge-eveatmo] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
```

**Version you use**
- homebridge version: 1.7.0
- node version: 20.10.0
- plugin version: latest

**To Reproduce**
Restart homebridge service

**Comment by mrmaximas** [comment]
anyone using api in two places at once like me? homebridge + node-red?

**Comment by jostrasser** [comment]
> anyone using api in two places at once like me? homebridge-eveatmo + node-red-contrib-netatmo-dashboard?

Yes, I am also using both: node-red and homebridge-eveatmo. :)

**Comment by jostrasser** [comment]
> I reset keys, deleted netatmo-token.json, generated a new access token with full r/w/a rights for all device types, put new client id, secret and refresh token into plugin settings and everything works again.

Have you tested a restart of the bridge? Is it solved permanently after creating the new tokens?

**Comment by mrmaximas** [comment]
> Have you tested a restart of the bridge? Is it solved permanently after creating the new tokens?

after full HB restart i have a problem again (((

**Comment by jostrasser** [comment]
> > Have you tested a restart of the bridge? Is it solved permanently after creating the new tokens?
> 
> after full HB restart i have a problem again (((

Yep, Is expected... :(

**Comment by jostrasser** [comment]
@skrollme 

Info from Netatmo DEV Support:

```
We just did a modification on the token retrieval process :
 
When you refreshed an access_token using the associated endpoint [https://api.netatmo.com/oauth2/token, Netatmo servers](https://api.netatmo.com/oauth2/token,%C2%A0Netatmo%C2%A0servers) responded with a couple of tokens : an access_token and a refresh_token. If the previous access_token was still valid, the refresh_token value was never renewed
 
Starting from the 04/12/2023, this behavior changed to be compliant with the recommendations of the [RFC of the OAuth2 Authorization Framework](https://www.rfc-editor.org/rfc/rfc6749) (section 10.4) and improving the security of the data of our users
When refreshing tokens, access_token and refresh_token values will be automatically renewed and former tokens invalidated
 
So, if you do not update and use the new refresh_token value when refreshing your access_token, your users will be disconnected after 3 hours and you will retrieve an “invalid_grant” error
To fix it, you need to update the tokens value as soon as you get the newly generated ones.
```

**Comment by mrmaximas** [comment]
> Yep, Is expected... :(

By the way i make additional "application" in dev.netatmo for NR.. Waiting for fix. 
In the new reality one token will not work in two systems as it will change after each request.

**Comment by fmarzocca** [comment]
> In the new reality one token will not work in two systems as it will change after each request.

Unless the 2 systems don't share the same json file with the tokens

**Comment by mrmaximas** [comment]
> Unless the 2 systems don't share the same json file with the tokens

they're two different systems.

**Comment by fmarzocca** [comment]
> they're two different systems.

yes, but there are many ways to share a file between 2 different systems (provided they are using the same Netatmo account)

**Comment by mrmaximas** [comment]
> many ways to share a file between 2 different systems
It won't work.
Each time the api is accessed, the token will be renew, and the second system will get the expired token.

**Comment by fmarzocca** [comment]
You need to save the file at each request, and to keep the json file synchronized between the 2 systems

**Comment by mrmaximas** [comment]
> You need to save the file at each request, and to keep the json file synchronized between the 2 systems

What's the point? I added a second app and now i have a couple of tokens that i can use at the frequency i need.

**Comment by fmarzocca** [comment]
> What's the point? I added a second app and have a couple of tokens that i can use at the frequency i need.

Good, no point. But you said before you said that "_one token will not work in two systems_ " and that's not true. Ok.

**Comment by mrmaximas** [comment]
> But you said before you said that "_one token will not work in two systems_ " and that's not true. Ok.

you are right, maybe it will work only in one case - when systems are unity and request data with the same frequency, but I have homebridge for homekit and node-red for export to influx then grafana.

**Comment by jostrasser** [comment]
Additional info from Netatmo:

```
The access_token must be refreshed every 3 hours (10800 seconds). This has always been the case
The difference was that if you refreshed your access_token before its expiration, refresh_token value always remained the same. If you wanted to refresh it but after expiration, the refresh_token value changed
 
Now, the 2 values change at each new /token request. So, you must catch the new generated refresh_token value each time a new request is done to the endpoint, and perform the next /token call with this new value
```

**Comment by Mindphazer73** [comment]
On my Netatmo app on my iPhone, I need to re-connect each time i use the app (I guess after the famous 3 hours)
What a great idea from Netatmo, if they want their users to run away :-(

**Comment by mrmaximas** [comment]
> On my Netatmo app on my iPhone, I need to re-connect each time i use the app (I guess after the famous 3 hours) What a great idea from Netatmo, if they want their users to run away :-(

I'm guessing it's not Netatmo's idea, but the very important Jedi Legrand engineers. :-)

**Comment by PvdGulik** [comment]
> On my Netatmo app on my iPhone, I need to re-connect each time i use the app (I guess after the famous 3 hours) What a great idea from Netatmo, if they want their users to run away :-(

I don't recognize this till now...... Maybe later.....

**Comment by Mindphazer73** [comment]
> I'm guessing it's not Netatmo's idea, but the very important Jedi Legrand engineers. :-)

Yeah you're probably right :-D

**Comment by Mindphazer73** [comment]
Well, it doesn't work for me
I still have invalid token access

**Comment by jostrasser** [comment]
@Mindphazer73 & @Pajonk100 

Please try the following:
1) Create a new Access and Refresh token with Postman
2) Manually enter both tokens into the `netatmo-token.json` file
3) Enter the same Refresh token into the `config.json` of Homebridge
4) Restart Homebridge service

This should actually work.

**Comment by PvdGulik** [comment]
I just created a new refresh token on dev.netatmo.com, and copied/pasted in Homebridge Eveatmo plugin in the settings, and voila, working again 😉
[07/12/2023, 18:29:53] [eveatmo platform] Initializing eveatmo platform...
[07/12/2023, 18:29:53] [eveatmo platform] Authenticating using 'refresh_token' grant
[07/12/2023, 18:29:57] [eveatmo platform] Loading new data from API for: weatherstation
[07/12/2023, 18:29:57] Loading 3 accessories...
________________________________
Van: Johannes Strasser ***@***.***>
Verzonden: donderdag 7 december 2023 18:21
Aan: skrollme/homebridge-eveatmo ***@***.***>
CC: Tebogo ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [skrollme/homebridge-eveatmo] Problem with the connection to Netatmo API since 2023-12-04 (Issue #77)


@Mindphazer73<https://github.com/Mindphazer73> & @Pajonk100<https://github.com/Pajonk100>

Please try the following:

  1.  Create a new Access and Refresh token with Postman
  2.  Manually enter both tokens into the netatmo-token.json file
  3.  Enter the same Refresh token into the config.json of Homebridge
  4.  Restart Homebridge service

This should actually work.

**Comment by Pajonk100** [comment]
> @Mindphazer73 & @Pajonk100
> 
> Please try the following:
> 
> 1. Create a new Access and Refresh token with Postman
> 2. Manually enter both tokens into the `netatmo-token.json` file
> 3. Enter the same Refresh token into the `config.json` of Homebridge
> 4. Restart Homebridge service
> 
> This should actually work.

problem was in netatmo-token.json - old tokens before my testing what was wrong... Now its working :) thx :D

**Comment by mrmaximas** [comment]
> @Mindphazer73 & @Pajonk100
> 
> Please try the following:
> 
> 1. Create a new Access and Refresh token with Postman
> 2. Manually enter both tokens into the `netatmo-token.json` file
> 3. Enter the same Refresh token into the `config.json` of Homebridge
> 4. Restart Homebridge service
> 
> This should actually work.

all Hombridge or plugin Bridge only?

**Comment by mrmaximas** [comment]
> > @Mindphazer73 & @Pajonk100
> > Please try the following:
> > 
> > 1. Create a new Access and Refresh token with Postman
> > 2. Manually enter both tokens into the `netatmo-token.json` file
> > 3. Enter the same Refresh token into the `config.json` of Homebridge
> > 4. Restart Homebridge service
> > 
> > This should actually work.
> 
> problem was in netatmo-token.json - old tokens before my testing what was wrong... Now its working :) thx :D

In my case it was always enough to delete netatmo-token.json and write a new refresh token

**Comment by jostrasser** [comment]
> all Hombridge or plugin Bridge only?

Only for the eveatmo plugin.

> In my case it was always enough to delete netatmo-token.json and put a new refresh token in plugin config

Should also work it the plugin is able to create it again. I ran into an issue in the past, that's the reason why I suggested to replace the keys. ;)

**Comment by mrmaximas** [comment]
> Only for the eveatmo plugin and a restart of the Homebridge service.
> 
> >

A couple of days ago it stopped working after a full restart of homebridge. Since I'm already tired of generating tokens, I'm not touching or restarting anything yet.

**Comment by jostrasser** [comment]
> A couple of days ago it stopped working after a full restart of homebridge. Since I'm already tired of generating tokens, I'm not touching or restarting anything yet.

Yes, I had the same behavior after a Homebridge restart. If the bridge is not restarted, everything should continue to run, also if Netatmo will redo the change.

The sticking point was the creation of new keys when the bridge restarts I think. So the goal should be to make it persistent again.

**Comment by skrollme** [comment]
Is this still an open case, @jostrasser ?

**Comment by jostrasser** [comment]
> Is this still an open case, @jostrasser ?

Hey @skrollme ,
Yes, I think so. If the API is inaccessible the plugin won't start / is hanging at "Starting".

It would be cool if you can add a timeout with a following retry (every 5mins) until the API comes back online. 

Thanks!

**Comment by skrollme** [comment]
> General: If the API is inaccessible the plugin won't start / is hanging at "Starting".

Correct, I think this is the main problem here. 

> It would be cool if you can add a timeout with a following retry (every 5mins) until the API comes back online. This would keep Homebridge up and running even if the API is not working correctly.

I'm not sure if the plugin's overall architecture supports this kind of approach. This would also be tricky to stage this environment/situation for testing purposes 🤔

**Comment by jostrasser** [comment]
> I'm not sure if the plugin's overall architecture supports this kind of approach. This would also be tricky to stage this environment/situation for testing purposes 🤔
> 

Understood. If there is no way to workaround a hanging startup of Homebridge if the API is down we only can disable the plugin until the API is back to get Homebridge back online (or we have to wait for the API). 

For me it's okay because I am backing up my HomeKit telemetry and can easily restore it even I loose the room assignments of the sensors. If you are planning to overwork the plugin: please keep this in mind as a feature request please 😉
