### ISSUE TITLE
Netatmo API changes imminent: May 29, 2024

### ISSUE THREAD

**Issue by johnny-tknoska** [skrollme/homebridge-eveatmo#79]
**Describe the bug**

Today (March 1, 2024) I received a mail from Netatmo with the next warning, so if no changes are made within the plugin code, it will finally stop working by May 29, 204

Dear Netatmo developer,
--
Today, when you refresh an Access Token using the associated endpoint https://api.netatmo.com/oauth2/token, the Netatmo servers respond with a pair of tokens: an Access Token and a Refresh Token.
If the previous Access Token is still valid, the newly returned access token is identical but has an expiration time extended by 3 hours.The Refresh Token is not renewed.

Starting May 29, 2024, this behavior will change to comply with the OAuth2 Authorization Framework RFC recommendations (section 10.4) and improve the security of our users' data.
When refreshing the tokens, the Access Token and Refresh Token will be different from the previous ones and the old tokens will be invalidated.

What does this mean for you?

If you already store the tokens returned by the API when refreshing your tokens, this change will not affect you.

If you do not update the tokens when refreshing them, your users will be logged out because the old tokens will be invalidated.

If for a given user, you have stored the same token in different places (for example: an application and its widget), you must have a way to synchronize them because the new token will be applied for the entire application.

**Comment by skrollme** [comment]
> If you already store the tokens returned by the API when refreshing your tokens, this change will not affect you.

This is alreadythe case in _homebridge-eveatmo_, so... 🤞
