### ISSUE TITLE
[enhancement] Netatmo welcome camera

### ISSUE THREAD

**Issue by DJay-X** [skrollme/homebridge-eveatmo#9]
Black Friday and of course the Netatmo welcome was also on sale. 🙄 So I bought it. dah.. For no particular reason.😉
Any chance to see a (the) camera supported in eveatmo in the very near future? 🤞🏻
Thx

**Comment by skrollme** [comment]
Currently no plan to implement this (because I do not own one). Aren't there other homebridge-plugins for the Welcome? Is it possible to use both: one for Sensors, one for camera?

**Comment by DJay-X** [comment]
I sold mine.Didn't liked it.  So also no need for me as well. ;) But thanks anyway for all your other work and sharing. 👍
